# Generated by Django 3.2.16 on 2022-11-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Player',
        ),
    ]
